Updated GitHub CI

diff --git a/.github/workflows/io-tests.yml b/.github/workflows/io-tests.yml
--- a/.github/workflows/io-tests.yml
+++ b/.github/workflows/io-tests.yml
@@ -54,6 +54,7 @@ jobs:
         cd core/IOTests
         swift package add-dependency "../.." --type path
         swift package add-target-dependency SwiftOSCIO IOTests --package "$PACKAGE_NAME"
+    # Don't run the build step otherwise it will exit with an error, since the I/O tests package only contains a test target
     # - name: Build
     #   run: |
     #     cd core/IOTests
@@ -63,83 +64,85 @@ jobs:
         cd core/IOTests
         xcodebuild test -skipMacroValidation -workspace "$IO_WORKSPACEPATH" -scheme "$IO_SCHEME" -destination "platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
   
-#  macCatalyst:
-#    name: I/O Tests (macCatalyst)
-#    runs-on: macos-latest
-#    timeout-minutes: 20
-#    steps:
-#    - uses: maxim-lobanov/setup-xcode@v1
-#      with:
-#        xcode-version: latest-stable
-#    - name: Clone Repo
-#      uses: actions/checkout@main
-#    - name: Clone I/O Tests
-#      uses: actions/checkout@main
-#      with:
-#        repository: orchetect/swift-osc-core
-#        ref: ${{ env.IO_REF }} # branch or commit hash
-#        sparse-checkout: IOTests # only downloads the IOTests folder from the repo root
-#        path: core # save to local subfolder
-#    - name: Set up I/O Tests
-#      run: |
-#        PACKAGE_NAME="${PWD##*/}"
-#        if [ -z $PACKAGE_NAME ]; then echo "⛔️ Error: Could not determine package name."; exit 1; fi
-#        cd core/IOTests
-#        swift package add-dependency "../.." --type path
-#        swift package add-target-dependency SwiftOSCIO IOTests --package "$PACKAGE_NAME"
-#    # - name: Build
-#    #   run: |
-#    #     cd core/IOTests
-#    #     xcodebuild build -skipMacroValidation -workspace "$IO_WORKSPACEPATH" -scheme "$IO_SCHEME" -destination "generic/platform=macOS,variant=Mac Catalyst" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-#    - name: Unit Tests
-#      run: |
-#        cd core/IOTests
-#        xcodebuild test -skipMacroValidation -workspace "$IO_WORKSPACEPATH" -scheme "$IO_SCHEME" -destination "platform=macOS,variant=Mac Catalyst" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-#
-#  device-simulators:
-#    name: I/O Tests
-#    runs-on: macos-latest
-#    strategy:
-#      matrix:
-#        target: [iOS, tvOS, watchOS, visionOS]
-#    continue-on-error: true
-#    timeout-minutes: 20
-#    steps:
-#    - uses: maxim-lobanov/setup-xcode@v1
-#      with:
-#        xcode-version: latest-stable
-#    - name: Prepare Device Simulator
-#      id: sim-setup
-#      uses: orchetect/setup-xcode-simulator@v1
-#      with:
-#        refresh: true
-#        download: true
-#        scheme: ${{ env.IO_SCHEME }}
-#        target: ${{ matrix.target }}
-#    - name: Clone Repo
-#      uses: actions/checkout@main
-#    - name: Clone I/O Tests
-#      uses: actions/checkout@main
-#      with:
-#        repository: orchetect/swift-osc-core
-#        ref: ${{ env.IO_REF }} # branch or commit hash
-#        sparse-checkout: IOTests # only downloads the IOTests folder from the repo root
-#        path: core # save to local subfolder
-#    - name: Set up I/O Tests
-#      run: |
-#        PACKAGE_NAME="${PWD##*/}"
-#        if [ -z $PACKAGE_NAME ]; then echo "⛔️ Error: Could not determine package name."; exit 1; fi
-#        cd core/IOTests
-#        swift package add-dependency "../.." --type path
-#        swift package add-target-dependency SwiftOSCIO IOTests --package "$PACKAGE_NAME"
-#    # - name: Build
-#    #   run: xcodebuild build -skipMacroValidation -workspace "$IO_WORKSPACEPATH" -scheme "$IO_SCHEME" -destination "generic/platform=$PLATFORMSHORT" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-#    #   env:
-#    #     PLATFORMSHORT: ${{ steps.sim-setup.outputs.platform-short }}
-#    #     WORKSPACEPATH: ${{ steps.sim-setup.outputs.workspace-path }}
-#    - name: Unit Tests
-#      run: xcodebuild test -skipMacroValidation -workspace "$IO_WORKSPACEPATH" -scheme "$IO_SCHEME" -destination "platform=$PLATFORM,id=$ID" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-#      env:
-#        ID: ${{ steps.sim-setup.outputs.id }}
-#        PLATFORM: ${{ steps.sim-setup.outputs.platform }}
-#        WORKSPACEPATH: ${{ steps.sim-setup.outputs.workspace-path }}
+  macCatalyst:
+    name: I/O Tests (macCatalyst)
+    runs-on: macos-latest
+    timeout-minutes: 20
+    steps:
+    - uses: maxim-lobanov/setup-xcode@v1
+      with:
+        xcode-version: latest-stable
+    - name: Clone Repo
+      uses: actions/checkout@main
+    - name: Clone I/O Tests
+      uses: actions/checkout@main
+      with:
+        repository: orchetect/swift-osc-core
+        ref: ${{ env.IO_REF }} # branch or commit hash
+        sparse-checkout: IOTests # only downloads the IOTests folder from the repo root
+        path: core # save to local subfolder
+    - name: Set up I/O Tests
+      run: |
+        PACKAGE_NAME="${PWD##*/}"
+        if [ -z $PACKAGE_NAME ]; then echo "⛔️ Error: Could not determine package name."; exit 1; fi
+        cd core/IOTests
+        swift package add-dependency "../.." --type path
+        swift package add-target-dependency SwiftOSCIO IOTests --package "$PACKAGE_NAME"
+    # Don't run the build step otherwise it will exit with an error, since the I/O tests package only contains a test target
+    # - name: Build
+    #   run: |
+    #     cd core/IOTests
+    #     xcodebuild build -skipMacroValidation -workspace "$IO_WORKSPACEPATH" -scheme "$IO_SCHEME" -destination "generic/platform=macOS,variant=Mac Catalyst" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+    - name: Unit Tests
+      run: |
+        cd core/IOTests
+        xcodebuild test -skipMacroValidation -workspace "$IO_WORKSPACEPATH" -scheme "$IO_SCHEME" -destination "platform=macOS,variant=Mac Catalyst" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+
+  device-simulators:
+    name: I/O Tests
+    runs-on: macos-latest
+    strategy:
+      matrix:
+        target: [iOS, tvOS, watchOS, visionOS]
+    continue-on-error: true
+    timeout-minutes: 20
+    steps:
+    - uses: maxim-lobanov/setup-xcode@v1
+      with:
+        xcode-version: latest-stable
+    - name: Prepare Device Simulator
+      id: sim-setup
+      uses: orchetect/setup-xcode-simulator@v1
+      with:
+        refresh: true
+        download: true
+        scheme: ${{ env.IO_SCHEME }}
+        target: ${{ matrix.target }}
+    - name: Clone Repo
+      uses: actions/checkout@main
+    - name: Clone I/O Tests
+      uses: actions/checkout@main
+      with:
+        repository: orchetect/swift-osc-core
+        ref: ${{ env.IO_REF }} # branch or commit hash
+        sparse-checkout: IOTests # only downloads the IOTests folder from the repo root
+        path: core # save to local subfolder
+    - name: Set up I/O Tests
+      run: |
+        PACKAGE_NAME="${PWD##*/}"
+        if [ -z $PACKAGE_NAME ]; then echo "⛔️ Error: Could not determine package name."; exit 1; fi
+        cd core/IOTests
+        swift package add-dependency "../.." --type path
+        swift package add-target-dependency SwiftOSCIO IOTests --package "$PACKAGE_NAME"
+    # Don't run the build step otherwise it will exit with an error, since the I/O tests package only contains a test target
+    # - name: Build
+    #   run: xcodebuild build -skipMacroValidation -workspace "$IO_WORKSPACEPATH" -scheme "$IO_SCHEME" -destination "generic/platform=$PLATFORMSHORT" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+    #   env:
+    #     PLATFORMSHORT: ${{ steps.sim-setup.outputs.platform-short }}
+    #     WORKSPACEPATH: ${{ steps.sim-setup.outputs.workspace-path }}
+    - name: Unit Tests
+      run: xcodebuild test -skipMacroValidation -workspace "$IO_WORKSPACEPATH" -scheme "$IO_SCHEME" -destination "platform=$PLATFORM,id=$ID" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+      env:
+        ID: ${{ steps.sim-setup.outputs.id }}
+        PLATFORM: ${{ steps.sim-setup.outputs.platform }}
+        WORKSPACEPATH: ${{ steps.sim-setup.outputs.workspace-path }}
